### ISSUE TITLE
Question about how to modify the default GPU

### ISSUE THREAD

**Issue by Richerhooders** [google/dynibar#6]
Thanks for your great work! In your code, I found that the default GPU number is zero：
`RuntimeError: CUDA out of memory. Tried to allocate 336.00 MiB (GPU 0; 31.75 GiB total capacity; 1.91 GiB already allocated; 212.00 MiB free; 2.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.

I attempted to modify -- local_ rank parameter and list (range (torch. cuda. device_count())) and reported an error：
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

Where else do I need to modify to change the default GPU0 to GPU1 or GPU2, GPU [1,2]?Thanks

**Comment by ShadowBbBb** [comment]
Hi, I would like to ask how you solved this? I met the same problem

**Comment by Richerhooders** [comment]
Hello, the author previously provided a response to address the issue of insufficient GPU memory，as follows：Hi, we experiment with 4X A100 GPUs with 40GB memory. If you want to train or test with less GPUs, you need to change "chunk_size" and "N_rand" in txt files to be smaller. However, we didn't test it with smaller sample sizes, so the final outcomes can be different.

**Comment by ShadowBbBb** [comment]
Thanks for the reply, i would like to know how to change the default GPU
I modify local_rank and list, but it returns the same error: RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

**Comment by Richerhooders** [comment]
I solved this problem before, but it's also a long time ago. You need to put the model and parameters on the same device. If you use multiple GPU devices, you need to put the data on the first device in the GPU list, except for modifying the local_ rank and list, you need to pay attention to the consistency between the GPU storing the model in ‘model.py’ and the GPU storing data in ’train.py‘.
